FlowersApp/Models/ErrorViewModel.cs
namespace FlowersApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FlowersApp/Models/FlowerModel.cs
using System.ComponentModel.DataAnnotations;

namespace FlowersApp.Models
{
    public class FlowerModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; }
        [Display(Name= "Availability")]
        public string Status { get; set; } = string.Empty;
        [Display(Name = "Number of Available Flowers")]
        public int StockQuantity { get; set; }
        public string Picture { get; set; } = string.Empty;
        public decimal Price { get; set;}
       
    }
}

FlowersApp/Models/OrderDetailsModel.cs
namespace FlowersApp.Models
{
    public class OrderDetailsModel
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public int ProductId { get; set; }
        public int OrderId { get; set; }

        public OrderModel Order {  get; set; }
        public FlowerModel Flower { get; set; }

    }
}

FlowersApp/Models/OrderModel.cs
using System.Collections;

namespace FlowersApp.Models
{
    public class OrderModel
    {
        public int Id { get; set; }
        public DateTime OrderPlaced { get; set; }
        public DateTime? OrderFulfilled { get; set; }
        public int CustomerId {  get; set; }

        public ICollection<OrderDetailsModel> OrderDetails {  get; set; }

    }
}

FlowersApp/Controllers/FlowerController.cs
using FlowersApp.Data;
using FlowersApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace FlowersApp.Controllers
{
    public class FlowerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FlowerController( ApplicationDbContext context)
        {
            
            _context = context;
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        } 
        public IActionResult Index()
        {
            var list_flowers = _context.Flowers.ToList();
           
                return View(list_flowers);
            
        }

        [HttpGet]
        public IActionResult InputForm()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(FlowerModel flower)
        {
            if (flower != null) 
            { 
            _context.Flowers.Add(flower);
            _context.SaveChanges();
            }
            return RedirectToAction("Index");

        }
        public IActionResult Details(int Id)
        {
            //error
            FlowerModel flower = _context.Flowers.FirstOrDefault(i => i.Id == Id);
            if (flower is null) { throw new Exception("the id could not be found"); }

            return View(flower);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var flower = _context.Flowers.FirstOrDefault(i => i.Id == id);
            return View(flower);
        }
        [HttpPost]
        public IActionResult Edit(FlowerModel Model)
        {
            
           var flower = _context.Flowers.Where(i => i.Id == Model.Id).FirstOrDefault();
            if (flower != null)
            {
                flower.Name = Model.Name;
                flower.Description = Model.Description;
                flower.Status = Model.Status;
                flower.StockQuantity = Model.StockQuantity;
                flower.Price = Model.Price;
                _context.SaveChanges();

            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var flower = _context.Flowers.Where(i => i.Id == id).FirstOrDefault();
            return View(flower);
        }
        [HttpPost]

        public IActionResult Delete(FlowerModel Model)
        {

            var flower = _context.Flowers.Where(i => i.Id == Model.Id).FirstOrDefault();
            if (flower != null)
            {
                _context.Flowers.Remove(flower);
                _context.SaveChanges();

            }
            return RedirectToAction("Index");
        }
        public IActionResult Search(string searchedTerm)
        {
            var flower= from g in _context.Flowers where g.Name.Contains(searchedTerm) select g;
            return View("Index",flower);
        }

    }
}

FlowersApp/Controllers/HomeController.cs
using FlowersApp.Data;
using FlowersApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FlowersApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
     
        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
        }   

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FlowersApp/Views/Flower/Delete.cshtml
@model FlowersApp.Models.FlowerModel
@{
    ViewData["Title"] = "Delete- Flower";

}
<div>
    <h4>Flower Detail</h4>
    <hr />
    <form asp-action="Delete">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
        <input type="submit" value="Delete" class="btn btn-outline-danger" onclick="if (!confirm('Are you sure?')) { return false }" />

    </form>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

FlowersApp/Views/Flower/Details.cshtml
@model FlowersApp.Models.FlowerModel
@{
    ViewData["Title"] = "Detail- Flower";
   
}
<div>
    <h4>Flower Detail</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @{string pic = Model.Name;
                pic = pic.Replace(" ", "");
                pic += ".png";
            }
            
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <div class="card" style="width: 18rem;">
        <img src="Model.Picture" class="card-img-top" alt="..." >
        </div>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Back to List</a>
</div>

FlowersApp/Views/Flower/Edit.cshtml
@model FlowersApp.Models.FlowerModel
@{
    ViewData["Title"] = "Edit - Flower";

}
<h4>Edit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockQuantity" class="control-label"></label>
                <input asp-for="StockQuantity" class="form-control" />
                <span asp-validation-for="StockQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
         
          
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FlowersApp/Views/Flower/Index.cshtml
@model IEnumerable<FlowerModel>
@{
    ViewData["Title"] = "List of flowers";
    int count = Model.Count();
}
 


<form asp-action="Search">

    <div class="SearchBar">
        <input name="searchedTerm"  class="form-control" placeholder="Which color are you looking for?" />
    </div>
    <br>
    <div class="form-group">
        <input type="submit" value="Search" class="btn btn-outline-primary" />
    </div>
</form>
<br>
<p>
    <a asp-action="InputForm" class="btn btn-outline-success">Create New</a>
</p>

<p> @count - Products</p>
<div class="container d-flex flex-wrap">
    @if ( Model != null ) {
    @foreach (var item in Model)
        {
            
            string pic = item.Name;
            pic = pic.Replace(" ", "");
            pic+=".png";
            <div class="card" style="width: 18rem;">
                <img src="@item.Picture" class="card-img-top" alt="..." width="150px" height="145px">
                <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <p class="card-text">@item.Description</p>
                <p class="card-text">@item.Price</p>

                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info">Show Details</a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-secondary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>

            </div>
        </div>
    }
    }
</div>

FlowersApp/Views/Flower/InputForm.cshtml
@model FlowerModel
@{
    ViewData["Title"] = "Create a Flower";

}
<h4>Add a Flower</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
       
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockQuantity" class="control-label"></label>
                <input asp-for="StockQuantity" class="form-control" />
                <span asp-validation-for="StockQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FlowersApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}

<div class="text-center">
   <h1 class="display-4">Welcome</h1>
   <p>Celebrate Your life and buy flowers</p>
   <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FlowersApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlowersApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" >
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/image/logo.png" width="42" height="42" style="vertical-align:top" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flower" asp-action="Index">Flowers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Flowers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>